title: CS 769
description: Fall 2026
theme: just-the-docs

url: "https://lucy3.github.io"
baseurl: "/cs769-fall26"

# Sidebar nav order
nav_sort: order

# Footer
footer_content: "CS 769 &mdash; Fall 2026"

# Search
search_enabled: false

# Color scheme: "light" or "dark"
color_scheme: light
